version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_dbfluxocaixa
    environment:
      POSTGRES_DB: dbFluxoCaixa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: 